version: '3.4'

services:

  users-identity:
    image: peimanpahleh/eshop-identity:0.1.2-beta.2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IdentityUrl=http://users-identity:80
      - ConsulCfg=true
      - ConsulKey=SampleEshop
      - VaultCfg=false
      - ServiceSettings__Consul=http://consul-server:8500
    ports:
      - "80"
      - "7278:443"
    volumes:
      - ./certs:/root/.aspnet/https:ro
    #command: dotnet /seed
    depends_on:
        - postgresql

  
  products-api:
    image: peimanpahleh/eshop-product:0.1.2-beta.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConsulCfg=true
      - ConsulKey=SampleEshop
      - VaultCfg=false
      - ServiceSettings__Consul=http://consul-server:8500
    ports:
      - "5010:80"
      - "5011:443"
    volumes:
      - ./certs:/root/.aspnet/https:ro
    depends_on:
        - users-identity
        - mongodb-primary
        - rabbitmq

  baskets-api:
    image: peimanpahleh/eshop-basket:0.1.2-beta.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConsulCfg=true
      - ConsulKey=SampleEshop
      - VaultCfg=false
      - ServiceSettings__Consul=http://consul-server:8500
    ports:
      - "5012:80"
    depends_on:
        - users-identity
        - products-api
        - mongodb-primary
        - rabbitmq

  orders-api:
    image: peimanpahleh/eshop-order:0.1.2-beta.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConsulCfg=true
      - ConsulKey=SampleEshop
      - VaultCfg=false
      - ServiceSettings__Consul=http://consul-server:8500
    ports:
      - "5014:80"
    depends_on:
        - users-identity
        - products-api
        - baskets-api
        - orders-saga
        - payments-api
        - mongodb-primary
        - rabbitmq

  orders-saga:
    image: peimanpahleh/eshop-order-saga:0.1.3-beta.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConsulCfg=true
      - ConsulKey=SampleEshop
      - VaultCfg=false
      - ServiceSettings__Consul=http://consul-server:8500
    depends_on:
        - mongodb-primary
        - rabbitmq

  
  payments-api:
    image: peimanpahleh/eshop-payment:0.1.2-beta.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConsulCfg=true
      - ConsulKey=SampleEshop
      - VaultCfg=false
      - ServiceSettings__Consul=http://consul-server:8500
    ports:
      - "5016:80"
    depends_on:
        - rabbitmq

  
  gateway:
    image: peimanpahleh/eshop-gateway:0.1.5-beta.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - UseConsul=true
      - Consul=http://consul-server:8500
    ports:
      - "5020:80"
    depends_on:
        - rabbitmq

      
  mongodb-primary:
    image: 'bitnami/mongodb:4.4.11-debian-10-r0'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=Pass123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-secondary:
    image: 'bitnami/mongodb:4.4.11-debian-10-r0'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=Pass123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    depends_on:
      - mongodb-primary   

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.4.11-debian-10-r0'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=Pass123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    depends_on:
      - mongodb-primary

  consul-server:
    image: consul
    container_name: consul-server    
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
     - ./server.json:/consul/config/server.json:ro
    command: "agent"

  postgresql:
    image: postgres:latest 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
    ports:
      - "5432:5432"
    volumes:
      - postgredata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692


volumes:
  mongo:
  postgredata:
  redis:
