version: "3.8"

services:

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo:/data/db

  mongodb-primary:
    image: 'bitnami/mongodb:4.4.11-debian-10-r0'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=Pass123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

    # volumes:
    #   - 'mongodb_master_data:/bitnami'

  mongodb-secondary:
    image: 'bitnami/mongodb:4.4.11-debian-10-r0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=Pass123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: 'bitnami/mongodb:4.4.11-debian-10-r0'
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=Pass123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  postgresql:
    image: postgres:latest 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
    ports:
      - "5432:5432"
    volumes:
      - postgredata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

  rabbitmq:
    image: masstransit/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      
volumes:
  # mongo:
  postgredata:
  redis:
